export { LandingPage } from './landing-page/LandingPage';
export { Rules } from './rules/Rules';
export { CategoryPage } from './category/Category';
export { Result } from './result/Result';
export { QuestionPage } from './question-page/QuestionPage';
export { QuizContainer } from './quiz-container/QuizContainer';
export { Login } from './login/Login';
export { Signup } from './signup/Singup';
export { Profile } from './profile/Profile';
